export const ALL_POKEMONS = "ALL_POKEMONS";
export const FILTER_TYPE = "FILTER_TYPE";
export const FILTER_APIORDB = "FILTER_APIORDB";
export const ORDER_ALPHABETICALLY = "ORDER_ALPHABETICALLY";
export const ORDER_ATTACK = "ORDER_ATTACK";
export const CREATE_POKEMON = "CREATE_POKEMON";